CHESTMNIST_LABEL = [
    "Aortic enlargement",
    "Pleural thickening",
    "Pleural effusion",
    "Cardiomegaly",
    "Lung Opacity",
    "Nodule/Mass",
    "Consolidation",
    "Pulmonary fibrosis",
    "Infiltration",
    "Atelectasis",
    "Other lesion",
    "ILD",
    "Pneumothorax",
    "Calcification",
]
